# Generated by Django 4.2.7 on 2023-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
